name: Get latest release version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/kubernetes-sigs/external-dns/tags | \
          jq -r ".[0] .name" > version.txt

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Github action'
          git config --global user.email 'zauberhaus@users.noreply.github.com'
          git commit -sam "Adding new release version" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
