name: Get latest release version
on:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        id: fetch
        run: |
            VERSION=$(curl -sL https://api.github.com/repos/kubernetes-sigs/external-dns/releases/latest | jq -r ".tag_name") && \
            echo ::set-output name=version::${VERSION} && \
            echo $VERSION > version.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          #git config --global user.name 'Your Name'
          #git config --global user.email 'your-email@users.noreply.github.com'
          git commit -am "New release version"
          git tag "${{ steps.fetch.outputs.version }}"
          git push origin "${{ steps.fetch.outputs.version }}"

