name: Get latest release version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Fetch release version
        id: fetch
        run: |
            VERSION=$(curl -sL https://api.github.com/repos/kubernetes-sigs/external-dns/releases/latest | jq -r ".tag_name") && \
            echo ::set-output name=version::${VERSION} && \
            echo -n $VERSION > version.txt

      - name: Check for modified files
        id: check
        run: |
            RESULT=$(git status --porcelain | grep "M version.txt" > /dev/null && echo -n "true" || echo -n "false")
            echo ::set-output name=modified::${RESULT}

      - name: Commit latest release version
        if: steps.check.outputs.modified == 'true'
        run: |
          echo "New version: ${{ steps.fetch.outputs.version }}"  
          git config --global user.name 'Github action'
          git config --global user.email 'zauberhaus@users.noreply.github.com'
          git add version.txt
          git commit -am "New external-dns version ${{ steps.fetch.outputs.version }}"
          git push origin HEAD
          git tag "${{ steps.fetch.outputs.version }}"
          git push origin "${{ steps.fetch.outputs.version }}"

